/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bookshopinventory;

import com.mycompany.bookshopinventory.constants.Constants;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import javax.swing.JOptionPane;

public class BuyItem extends javax.swing.JFrame {

    private double price;
    private int totalQuantity;
    private String category;
    private String username;
    private ResultSet rs = null;
    private PreparedStatement ps = null;
    private Connection conn = null;
    private final String INSERT_EXPENDITURE_SQL = "INSERT INTO purchasetbl"
            + "  (username, bookshop_item, quantity, price) VALUES "
            + " (?,?,?,?);";
    private final String UPDATE_STOCK_SQL = "UPDATE stocktbl "
            + "SET quantity=?"
            + "WHERE bookshop_item = ?";

    private final String DISPLAY_STOCK_SQL = "SELECT bookshop_item FROM stocktbl ORDER BY bookshop_item ASC";
    private final String DISPLAY_ITEM_SQL = "SELECT quantity, price FROM stocktbl WHERE bookshop_item = ?";

    /**
     * Creates new form Expenditure
     */
    public BuyItem() {
        initComponents();
    }

    public BuyItem(String username) {
        initComponents();
        this.username = username;
        listData();
    }

    private void listData() {
        try {
            conn = DriverManager.getConnection(Constants.url, Constants.user, Constants.password);
            ps = conn.prepareStatement(DISPLAY_STOCK_SQL);
            rs = ps.executeQuery();
            while (rs.next()) {
                String str = rs.getString("bookshop_item");
                jComboCategory.addItem(str);
            }
            ps.close();
            rs.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboCategory = new javax.swing.JComboBox<>();
        jTxtQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnAdd = new javax.swing.JButton();
        jLabelPrice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnHistory1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Purchase Item");

        jComboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        jComboCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboCategoryItemStateChanged(evt);
            }
        });
        jComboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoryActionPerformed(evt);
            }
        });

        jTxtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtQuantityFocusLost(evt);
            }
        });
        jTxtQuantity.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTxtQuantityInputMethodTextChanged(evt);
            }
        });
        jTxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantityActionPerformed(evt);
            }
        });
        jTxtQuantity.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTxtQuantityPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Bookshop Item");

        jBtnAdd.setText("Purchase");
        jBtnAdd.setEnabled(false);
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrice.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Price");

        jBtnHistory1.setText("View Purchase");
        jBtnHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHistory1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPrice)
                                    .addComponent(jTxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnHistory1)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd)
                    .addComponent(jBtnHistory1))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboCategoryItemStateChanged
        if (jComboCategory.getSelectedIndex() > 0) {
            category = jComboCategory.getSelectedItem().toString();
            jBtnAdd.setEnabled(true);
            try {
                conn = DriverManager.getConnection(Constants.url, Constants.user, Constants.password);
                ps = conn.prepareStatement(DISPLAY_ITEM_SQL);
                ps.setString(1, category);
                rs = ps.executeQuery();
                if (rs.next()) {
                    price = rs.getDouble("price");
                    totalQuantity = rs.getInt("quantity");
                    jTxtQuantity.setText("1");
                    jLabelPrice.setText(String.valueOf(price));
                }
                ps.close();
                rs.close();
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            jBtnAdd.setEnabled(false);
            jTxtQuantity.setText("");
            jLabelPrice.setText("0");
        }
    }//GEN-LAST:event_jComboCategoryItemStateChanged

    private void jComboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoryActionPerformed

    }//GEN-LAST:event_jComboCategoryActionPerformed

    private void jTxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantityActionPerformed
        try {
            Integer quantity = Integer.parseInt(jTxtQuantity.getText().trim());
            double myprice = quantity * price;
            jLabelPrice.setText(String.valueOf(myprice));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnAdd, "Enter a valid quantity");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTxtQuantityActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        double myprice = 0;
        Integer quantity = 0;
        try {
            quantity = Integer.parseInt(jTxtQuantity.getText().trim());
            myprice = quantity * price;
            if (quantity <= totalQuantity) {
                try {
                    int newQuantity = totalQuantity - quantity;
                    conn = DriverManager.getConnection(Constants.url, Constants.user, Constants.password);
                    ps = conn.prepareStatement(INSERT_EXPENDITURE_SQL);
                    ps.setString(1, username);
                    ps.setString(2, category);
                    ps.setInt(3, quantity);
                    ps.setDouble(4, myprice);
                    ps.executeUpdate();
                    ps = conn.prepareStatement(UPDATE_STOCK_SQL);
                    ps.setInt(1, newQuantity);
                    ps.setString(2, category);
                    ps.executeUpdate();
                    ps.close();
                    conn.close();
                    JOptionPane.showMessageDialog(jBtnAdd, "Data Saved");
                    jTxtQuantity.setText("");
                    jBtnAdd.setEnabled(false);
                    jComboCategory.setSelectedIndex(0);
                    ps.close();
                    rs.close();
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(jBtnAdd, "Out of Stock");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnAdd, "Enter a valid quantity");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHistory1ActionPerformed
        setVisible(false);
        new ViewHistory(username).setVisible(true);
    }//GEN-LAST:event_jBtnHistory1ActionPerformed

    private void jTxtQuantityInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTxtQuantityInputMethodTextChanged
    }//GEN-LAST:event_jTxtQuantityInputMethodTextChanged

    private void jTxtQuantityPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTxtQuantityPropertyChange

    }//GEN-LAST:event_jTxtQuantityPropertyChange

    private void jTxtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtQuantityFocusLost
        try {
            Integer quantity = Integer.parseInt(jTxtQuantity.getText().trim());
            double myprice = quantity * price;
            jLabelPrice.setText(String.valueOf(myprice));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnAdd, "Enter a valid quantity");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTxtQuantityFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnHistory1;
    private javax.swing.JComboBox<String> jComboCategory;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JTextField jTxtQuantity;
    // End of variables declaration//GEN-END:variables

}
